Repository DeveloperAcademy-POSTECH/MC3-Team12-MeDrop, pull requests merged in 2023-07, with the labels that each got.

#12 애플 로그인 구현
  MeDrop/MeDrop.xcodeproj/project.pbxproj
  MeDrop/MeDrop/MeDrop.entitlements
  MeDrop/MeDrop/Sources/Components/AppleSignInButton/AppleSignInButton.swift
  MeDrop/MeDrop/Sources/Util/Extensions/Extension+UIApplication.swift
  MeDrop/MeDrop/Sources/Util/Extensions/Extension+UIScreen.swift
  MeDrop/MeDrop/Sources/Util/Utility/Utility.swift
Labels: 🤷 Kayle

#23 메인 화면 구현
  MeDrop/MeDrop.xcodeproj/project.pbxproj
  MeDrop/MeDrop/Resources/Assets.xcassets/ProfileCardImage/Contents.json
  MeDrop/MeDrop/Resources/Assets.xcassets/ProfileCardImage/HorizontalPattern.imageset/Contents.json
  MeDrop/MeDrop/Resources/Assets.xcassets/ProfileCardImage/HorizontalPattern.imageset/HorizontalPattern 1.png
  MeDrop/MeDrop/Resources/Assets.xcassets/ProfileCardImage/HorizontalPattern.imageset/HorizontalPattern.png
  MeDrop/MeDrop/Resources/Assets.xcassets/ProfileCardImage/VerticalPattern.imageset/Contents.json
  MeDrop/MeDrop/Resources/Assets.xcassets/ProfileCardImage/VerticalPattern.imageset/Rectangle 1.png
  MeDrop/MeDrop/Resources/Assets.xcassets/ProfileCardImage/VerticalPattern.imageset/Rectangle.png
  MeDrop/MeDrop/Sources/Collection/View/CollectionView.swift
  MeDrop/MeDrop/Sources/Collection/View/Extension+CollectionView.swift
  MeDrop/MeDrop/Sources/Collection/ViewModel/CollectionViewModel.swift
  MeDrop/MeDrop/Sources/My/View/Extension+MyView.swift
  MeDrop/MeDrop/Sources/My/View/MyView.swift
  MeDrop/MeDrop/Sources/My/View/ProfileCardViewRatio.swift
  MeDrop/MeDrop/Sources/My/ViewModel/MyViewModel.swift
  MeDrop/MeDrop/Sources/Util/Extensions/Extension+CGFloat.swift
  MeDrop/MeDrop/Sources/Util/Extensions/Extension+View.swift
Labels: In review

#56 :clap:: 교환 뷰 상태별 뷰 합치기 완료
  MeDrop/MeDrop.xcodeproj/project.pbxproj
  MeDrop/MeDrop/Resources/Assets.xcassets/RequestImage/Contents.json
  MeDrop/MeDrop/Resources/Assets.xcassets/RequestImage/RequestJelly.imageset/Contents.json
  MeDrop/MeDrop/Resources/Assets.xcassets/RequestImage/RequestJelly.imageset/Group 1188-1.png
  MeDrop/MeDrop/Resources/Assets.xcassets/RequestImage/RequestJelly.imageset/Group 1188.png
  MeDrop/MeDrop/Resources/DesignSystem/DesignSystemAsset.swift
  MeDrop/MeDrop/Resources/Loading.json
  MeDrop/MeDrop/Sources/Components/Toast/Toast.swift
  MeDrop/MeDrop/Sources/Components/Toast/ToastModifier.swift
  MeDrop/MeDrop/Sources/Components/Toast/ToastView.swift
  MeDrop/MeDrop/Sources/ContentView.swift
  MeDrop/MeDrop/Sources/Exchange/Model/ExchangeDataModel.swift
  MeDrop/MeDrop/Sources/Exchange/View/ExchangeView.swift
  MeDrop/MeDrop/Sources/Exchange/ViewModel/ExchangeViewModel.swift
  MeDrop/MeDrop/Sources/MeDropApp.swift
  MeDrop/MeDrop/Sources/Share/View/ShareView.swift
  MeDrop/MeDrop/Sources/Share/ViewModel/ShareViewModel.swift
  MeDrop/MeDrop/Sources/Util/Extensions/Extension+View.swift
Labels: 👀 view, ⚙️ function, 📀 data
